### ISSUE TITLE
Organisation offerings shows no offerings 

### ISSUE THREAD

**Issue by mattronix** [waldur/waldur-mastermind#51]
On the Organization offering page, even if i unselect the two filters that are set by default i do not see any offering from my organisation, on the admin Offering page i do see them, they are also created from the add new offering button on the screenshot below: 

![image](https://github.com/waldur/waldur-mastermind/assets/1733023/6d06f055-f5b7-4ab1-b34f-cb7d60752709)

**Comment by livenson** [comment]
actually, the bug is that the buttons are shown
My Offerings is a bit complex thing, they represent "bulk purchases" done by organizations. I.e. organization can create resources from them - e.g. VMs in OpenStack Tenant - but they will not be billed to organization.

Thanks for reporting, it is some regression, at the moment we do not allow direct registration of such offerings, they are created in a workflow if specific offering supports it.

**Comment by mattronix** [comment]
Ah i see, no problem :) just thought id report what i find hahaha : )
